---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-dev
  namespace: argocd
spec:
  project: oneplatform
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.7.19
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-dev
  namespace: argocd
spec:
  project: oneplatform
  source:
    repoURL: https://otwld.github.io/ollama-helm/
    chart: ollama
    targetRevision: 0.66.0
    helm:
      values: |
        ollama:
          gpu:
            enabled: false
          models:
            pull: ["llama3.1:8b"]
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-dev
  namespace: argocd
spec:
  project: oneplatform
  source:
    repoURL: https://kserve.github.io/helm-charts
    chart: kserve
    targetRevision: 0.13.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
