{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "calculator-backend.fullname" . }}
  labels:
    {{- include "calculator-backend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "calculator-backend.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "{{ .Values.keda.cpuThreshold }}"
{{- end }}
