apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator-frontend.fullname" . }}
  labels:
    {{- include "calculator-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calculator-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calculator-frontend.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet: { path: {{ .Values.probes.readiness.path }}, port: http }
          livenessProbe:
            httpGet: { path: {{ .Values.probes.liveness.path }}, port: http }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop:
                {{- toYaml .Values.securityContext.capabilities.drop | nindent 16 }}
