apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: math-ocr
  namespace: mlops
spec:
  predictor:
    model:
      modelFormat: { name: sklearn }
      storageUri: "s3://mlflow-artifacts/math-ocr/latest"
      resources:
        requests: { cpu: 100m, memory: 256Mi }
        limits:   { cpu: 1,    memory: 1Gi }
