apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneplatform-staging
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: oneplatform
  source:
    repoURL: https://github.com/RajeshPat87/oneplatform_k8s
    targetRevision: main
    path: argocd-apps/staging
    directory:
      recurse: true
      exclude: 'app-of-apps.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
