server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/backend/ {
        proxy_pass http://calculator-backend.apps.svc.cluster.local:8000/;
        proxy_set_header Host $host;
    }

    location /api/ai/ {
        proxy_pass http://calculator-ai-service.apps.svc.cluster.local:8001/;
        proxy_set_header Host $host;
    }
}
