name: ci-frontend-$(Date:yyyyMMdd)-$(Rev:rr)

trigger:
  branches:
    include: [main]
  paths:
    include:
      - apps/calculator-frontend/*
      - helm/calculator-frontend/*
      - .azure-pipelines/ci-frontend.yml
      - .azure-pipelines/templates/*

pr:
  paths:
    include:
      - apps/calculator-frontend/*
      - helm/calculator-frontend/*

variables:
  - group: oneplatform-common
  - name: APP
    value: calculator-frontend
  - name: APP_DIR
    value: apps/calculator-frontend

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Verify
    jobs:
      - job: LintTest
        steps:
          - template: templates/node-lint-test.yml
            parameters:
              appDir: $(APP_DIR)

      - job: SAST
        steps:
          - template: templates/sast-semgrep.yml
            parameters:
              config: 'p/ci p/javascript p/react'

  - stage: BuildPush
    dependsOn: Verify
    condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Image
        steps:
          - template: templates/docker-build-scan-push.yml
            parameters:
              app: $(APP)
              appDir: $(APP_DIR)
              acrLoginServer: $(ACR_LOGIN_SERVER)
          - template: templates/gitops-bump.yml
            parameters:
              app: $(APP)
              env: dev
